### ISSUE TITLE
Completely wrong code!

### ISSUE THREAD

**Issue by s0urfruit** [Elmue/WindowsRT-GUID-Analyzer#1]
You code is full of bugs and the code is not finished.

This line throws an error!
`static String SDK_PATH   = "E:\\Windows SDK\\Include\\10.0." + SDK_BUILD + ".0\\";`

It looks like shit!

Did you ever test you code before uploading it?

Did you not notice that your code does not work
AT ALL?

Or don't you care and think you are cool when you fill Github with complete garbage code?

Either you finish a project and make sure that it works.

Or you do NOT upload it to Github.
Please delete this garbage from Github.

It is not useful for ANYBODY.

**Comment by s0urfruit** [comment]
Please delete this garbage code from GitHub. In fact, delete your account and start over. Perhaps a different career?

**Comment by marsidev** [comment]
Finish a project and make sure that it works.

Or you do NOT upload it to Github.
Please delete this garbage from Github.

It is not useful for ANYBODY.
